### ISSUE TITLE
Can I fork this for a firefox add-on?

### ISSUE THREAD

**Issue by tadast** [jarques/Hacker-News--#8]
Hi,
I have recently switched to Firefox and missed this browser extension a bit. There is no license in the repo, so I wanted to ask if it would be ok if I forked this and released an add-on for Firefox, with proper attributions of course. 

What do you think?

**Comment by jarques** [comment]
:+1: Sure!

**Comment by tadast** [comment]
Awesome, thanks. https://github.com/tadast/Firefox-Hacker-News-plus-plus let me know if you want me to change anything in the readme.
